In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pickle

In [15]:
df=pd.read_excel(r"E:\results.xlsx")

In [16]:
X=df.drop(['label'],axis=1)
y=df[['label']]
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3)


In [17]:
lm=LinearRegression()
clf=DecisionTreeClassifier()
reg=DecisionTreeRegressor()

In [18]:
def enter_data():
   
    ph_val=float(input("enter ph data"))
    temp_val=float(input("enter temperature of soil"))
    humidity_val=float(input("enter humidity"))
    rainfall_val=float(input("enter rainfall"))
    moisture_val=float(input("enter moisture "))
    
    #y_test=list((ph_val,temp_val,humidity_val,rainfall_val,moisture_val))
    y_test= [[ph_val,temp_val,humidity_val,rainfall_val,moisture_val]]
    decode(predict(y_test))
    #print(y_test)
    return y_test

In [25]:
enter_data()

enter ph data6.5
enter temperature of soil32
enter humidity89
enter rainfall150
enter moisture 90
corn


[[6.5, 32.0, 89.0, 150.0, 90.0]]

In [19]:
lm.fit(x_train,y_train)
clf.fit(x_train,y_train)
reg.fit(x_train,y_train)

In [20]:

x1=lm.predict(x_test)
x2=clf.predict(x_test)
x3=reg.predict(x_test)

In [21]:
def predict(y):
    pred1=clf.predict(y)
    pred2=reg.predict(y)
    pred3=lm.predict(y)
    return pred2


In [22]:
def decode(value):
     for i in value:
        if i<=1.5:
            print("paddy")
        elif i<=2.5:
            print("corn")
        elif i<=3.5:
            print("potato")
        elif i<=4.5:
            print("tomato")
    

In [24]:
decode(pred1)
print("--------")
decode(pred2)
print("--------")
decode(pred3)

NameError: name 'pred1' is not defined

In [13]:
confusion_matrix(y_test, x3)

array([[1, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 3]], dtype=int64)

In [14]:
confusion_matrix(y_test, x2)

array([[1, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 3]], dtype=int64)

In [15]:
accuracy_score(y_test, x3)*100
accuracy_score(y_test, x2)*100

100.0

In [29]:
filename='crop_prediction.sav'
model=pickle.load(open(filename,'rb'))
decode(model.predict(enter_data()))

enter ph data0
enter temperature of soil0
enter humidity0
enter rainfall0
enter moisture 0
paddy
paddy


In [27]:
decode(predict(enter_data()))

enter ph data6.5
enter temperature of soil32
enter humidity89
enter rainfall150
enter moisture 90
corn
corn


array([129.737])